version: '2'
services:
  web:
    image: docker-node-express-mongoapp
    build: .
    command: node server.js
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/  
      - /usr/src/node_modules
    depends_on:
      - "mongo"
    networks:
      - nd
  
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:  
      - './data:/data/db'  
    networks:
      - nd

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    networks:
      - nd

networks:  
  nd:
    driver: bridge